### ISSUE TITLE
import zipcodes gives a TypeError

### ISSUE THREAD

**Issue by Lvl4Sword** [seanpianka/Zipcodes#1]
TypeError: the JSON object must be str, not 'bytes'

**Comment by abuchanan920** [comment]
I'm receiving the same error when running within an Ubuntu Xenial based docker container with Python 3.5. It ran fine locally on my Mac under Python 3.6.4 (Anaconda).

**Comment by gwaramadze** [comment]
confirming, just got the same on `Python 3.5.3`

**Comment by seanpianka** [comment]
Apologies for the delay, I'll begin working on a patch for Python 3.5.* now.

**Comment by seanpianka** [comment]
@Lvl4Sword @abuchanan920 @gwaramadze This issue should now be resolved for Python 3.5.* and (hopefully) any older versions that were experiencing these issues.
