### ISSUE TITLE
Timezone information.

### ISSUE THREAD

**Issue by IlyaSukhanov** [seanpianka/Zipcodes#2]
It would be really handy if timezone info was also available for zip codes. This information is available through https://github.com/buckmaxwell/zipcode and can probably be compiled to zips.json.gz.

Is this data omitted for a reason (such as storage requirements)? If PR was made to introduce this data, would it be accepted? It may also be possible to compute out time based of lat-long of zipcode and see if its in the shapefile of a timezone.

Is there information about how zips.json.gz was compiled?

**Comment by seanpianka** [comment]
I will certainly look into adding this information into the newest version, assuming it's not a massive bloom in the size of `zips.json.gz`.

**Comment by seanpianka** [comment]
Timezone information is now available during zipcode lookup. Please see the README for details.
